config/routes.rb
Rails.application.routes.draw do
  get 'login' => "login#login", as: "login"
  get 'logout' => "login#logout", as: "logout"
  post 'auth' => "login#auth", as: "login_auth"
  get 'usuario/new'
  get 'usuario/show/:id' => "usuario#show", as: "usuario_show"
  post 'usuario/create'
  get 'menu/page1'
  get 'menu/page2'
  get 'menu/page3'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    VALID_EMAIL = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :email, presence: true, length: { minimum: 5 },
        format: { with: VALID_EMAIL }, uniqueness: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  include LoginHelper
  
  def login
  end

  def logout
    log_out
    redirect_to root_path
  end

  def auth
    # @parametros = {email: "teste@teste.com",password: "122"}
    @parametros = login_params
    @user = Usuario.find_by(email: @parametros[:email])
    if(@user && @user.authenticate(@parametros[:password]))
      log_in @user
      redirect_to usuario_show_path(@user)
    else
      redirect_to login_path
    end
  end
  
  private 
    def login_params
      # VAI LER OS CONTEUDOS ESCRITOS NOS CAMPOS DO FORM
      params.require(:login).permit(:email, :password)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  include LoginHelper
  
  # before_action :logged_in?, only: [:page1, :page3]
  
  def page1
    logged_in?("page1")
  end

  def page2
  end

  def page3
    logged_in?("page3")
  end
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  def new
    @user = Usuario.new
  end

  def show
    @user = Usuario.find(params[:id])
  end

  def create
    @user = Usuario.new(user_params)
    if @user.save 
      redirect_to usuario_show_path(@user)
    else
      render "new"
    end
  end
  
  private

    def user_params
      # VAI LER OS CONTEUDOS ESCRITOS NOS CAMPOS DO FORM
      params.require(:usuario).permit(:nome, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
        session.delete(:user_id)
    end
    
    def logged_in?(page)
        if(!session[:user_id].nil?)
            render page
        else 
            redirect_to login_path
        end
    end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/views/application/index.html.erb
<h1>AULA6!!!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/auth.html.erb
<h1>Login#auth</h1>
<p><%= @user %></p>

app/views/login/login.html.erb
<h1>Faça seu login</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:login, url: login_auth_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Login", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/login/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>

app/views/menu/page1.html.erb
<h1>Menu#page1</h1>
<p>Find me in app/views/menu/page1.html.erb</p>

app/views/menu/page2.html.erb
<h1>Menu#page2</h1>
<p>Find me in app/views/menu/page2.html.erb</p>

app/views/menu/page3.html.erb
<h1>Menu#page3</h1>
<p>Find me in app/views/menu/page3.html.erb</p>

app/views/usuario/create.html.erb
<h1>Usuario#create</h1>
<p>Find me in app/views/usuario/create.html.erb</p>

app/views/usuario/new.html.erb
<h1>Cadastro de Usuario</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: usuario_create_path) do |f| %>
      <%= f.label :nome %>
      <%= f.text_field :nome %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Criar conta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/usuario/show.html.erb
<h1>Usuario <%= @user.nome %></h1>

<h2>E-mail: <%= @user.email %></h2>